### ISSUE TITLE
react-service doesn't support host setting

### ISSUE THREAD

**Issue by BenAtEventbrite** [mic159/react-render#3]
The documentation says that you can specify the `--host` setting to override the default `localhost` for the `react-service`, but that doesn't actually work. 🙁 In looking at the [code](https://github.com/mic159/react-render/blob/master/render.js#L94), it looks like the call to `app.listen` has `'localhost'` hardcoded instead of something like `argv.host || 'localhost'`.

Is this something that can be updated and published to npm?

Thanks!

**Comment by mic159** [comment]
Sure thing, I'll push a new version soon

**Comment by mic159** [comment]
@BenAtEventbrite Thanks for reporting the inconsistency.
I have added a `--host` option and published 0.12.4 on npm now.

**Comment by BenAtEventbrite** [comment]
Working as expected! Thanks for the quick fix!
