### ISSUE TITLE
Example app fails at npm run react-render-service

### ISSUE THREAD

**Issue by aleccunningham** [mic159/react-render#5]
As the title states, when running the example app, npm crashes when trying to start the render server. The debug log is http://pastebin.com/7DutC41j . The Django server runs...I'm questioning whether it's an issue with using a virtualenv for python dependencies vs npm packages?

**Comment by mic159** [comment]
Thanks for reporting, I will look into this shortly.

**Comment by mic159** [comment]
I thought it might have something to do with using nodejs 6 (i have been using 4).
But I just upgraded to 6 and it all appears to be working correctly.

Can you show me the output if you just run `node render.js` by itself, instead of through npm run?

render.js is in the root directory of this repository.

**Comment by aleccunningham** [comment]
<img width="573" alt="screen shot 2016-05-04 at 7 15 29 pm" src="https://cloud.githubusercontent.com/assets/512428/15033050/9ba7f80c-122c-11e6-81b1-99290eb7e0db.png">

**Comment by aleccunningham** [comment]
Just pulled down the repo again and it worked this time...werid.

**Comment by mic159** [comment]
The express error is because your `node_modules` is inside example. So can you try running `node ../render.js` from inside the examples directory?

**Comment by mic159** [comment]
It's been a while, so I'm assuming you worked it out.
If not, please feel free to re-open this issue and we will continue debugging.

Thanks for trying out react-render!
