### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by flyalex** [mic159/react-render#7]
Hi!

Seems this component works on my side, but if I change code to ES6, node throws error:

```
[2016-05-16T17:56:18.227Z] Loading new component /Users/Alex/Desktop/venvfolder/webdev/mywebsite/website/static/js/main.server.js
[2016-05-16T17:56:18.243Z] TypeError: Cannot read property 'render' of undefined
```

This code works:
```js
var React = require('react');

module.exports = React.createClass({
	render: function() {
		return (<div><h1>This works!</h1></div>);
	}
});
```

This code doesn't work:
```js
import React from 'react';

export default class Main extends React.Component {
   render() {
       return (<div><h1>Does not work</h1></div>);
    }
}
```

**Comment by mic159** [comment]
Yes unfortunately that is correct.
React render currently expects the base export object itself to be the component.

I think we should change it to support default exports.
Unfortunately I cant do this for a few weeks.

When I am able to, I will make a new version for this.

Thanks for reporting!

**Comment by mic159** [comment]
However, you can use ES6 class components. It's just the export that's the problem.

This should work:

```
import React from 'react';

class Main extends React.Component {
   render() {
       return (<div><h1>Does not work</h1></div>);
    }
}

module.exports = Main;
```

**Comment by mic159** [comment]
I have a fix for the `export default` ready to go along with some minor tweaks and version bumps.

I will do some more testing tomorrow morning then release the new version.

**Comment by mic159** [comment]
I have pushed a new release to NPM with a fix for this. Sorry for taking so long to do it!

https://github.com/mic159/react-render/blob/master/CHANGELOG.md#0131
https://github.com/mic159/react-render/releases/tag/0.13.1
https://github.com/mic159/react-render/compare/0.13.0...0.13.1
https://www.npmjs.com/package/react-render-service

**Comment by flyalex** [comment]
Thank you! :)
