### ISSUE TITLE
Some issue with ES6

### ISSUE THREAD

**Issue by Darwesh27** [mic159/react-render#8]
Here is the code.

```
import React from "react";
import NavBar from "./components/Navbar"

class App extends React.Component {
    render(){
        return (
            <div>
                {this.props.children}
            </div>
        );
    }
}

export default App
```

and here is the error that node app raises. 

> import React from 'react';
> ^^^^^^
> [2016-06-21T12:12:11.873Z] SyntaxError: Unexpected reserved word
>

**Comment by mic159** [comment]
Are you using webpack (or similar) to build the server-side components, or attempting to directly render the JSX file?

**Comment by Darwesh27** [comment]
I am attempting to directly render the file.

**Comment by mic159** [comment]
Unfortunately, NodeJS does not support `import` statements yet. You will need to use something like webpack/babel to transform your code into something NodeJS can run (CommonJS `require` calls).

Even if you changed your import statements to require, NodeJS can't read JSX syntax anyway.

Have a look at the webpack configuration in the example directory of this repo for a guide.
